server:
  port: 8080

spring:
  security:
    jwt:
      secret-key: "fc742567347be08a47bd753fbeb93771655c2de494a36fdc661a46f7482b2bc1"
      expiration: 900000
      refresh-expiration: 604800000

  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/intelligent_course
    username: postgres
    password: "012402"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

